openapi: "3.0.1"

info:
  title: "OpenWeatherMap API"
  description: "Sample OpenWeather API."
  version: "2.5"
  termsOfService: "https://openweathermap.org/terms"
  license:
    name: "Sample Liscense"
    url: "https://openweathermap.org"
    
tags:
  - name: Current Weather Data
    description: "Get current weather details"

externalDocs:
  description: API Documentation
  url: https://openweathermap.org/api

servers:
- url: "https://api.openweathermap.org/data/2.5/"

security:
- app_id: []

# Path Defination for API

paths:
  /weather:
    get:
      tags:
      - Current Weather Data
      summary: "Call current weather data for one location"
      description: "Get the current weather info"
      operationId: CurrentWeatherData
      parameters:
        - in: query 
          name: lat
          description: "For the query value, type the location latitude. Example: 43.13"
          schema:
            type: number
            default: 43.13
          required: true
        - in: query
          name: lon
          description: "For the query value, type the location longitude. Example: 70.92"
          schema:
            type: number
            default: -70.92
          required: true
        - in: query
          name: appid
          description: "For the query value, type your API key. Example: 32 hexidecimal digits"
          schema:
            type: string
            default: ""
          required: true
          
      responses:
        200:
          description: Successful response
          content:
            application/json: {}

        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found

components:
  securitySchemes:
    app_id:
      type: apiKey
      description: API key to authorize requests. If you don't have an OpenWeatherMap API key, use `0e42a4c3dff34f7e42dbfcd804a5c917`
      name: appid
      in: query
