openapi: "3.0.1"

info:
  title: "OpenWeatherMap API"
  description: "Sample OpenWeather API."
  version: "2.5"
  termsOfService: "https://openweathermap.org/terms"
  license:
    name: "Sample Liscense"
    url: "https://openweathermap.org"
    
tags:
  - name: Current Weather Data
    description: "Get current weather details"

externalDocs:
  description: API Documentation
  url: https://openweathermap.org/api

servers:
- url: "https://api.openweathermap.org/data/2.5/"

# Path Defination for API

paths:
  /weather:
    get:
      security:
      - app_id: []
      tags:
      - Current Weather Data
      summary: "Call current weather data for one location"
      description: "Get the current weather info"
      operationId: CurrentWeatherData
      parameters:
        - in: query 
          name: zip
          description: "For the query value, type the US based zipcode. Example: 03824"
          schema:
            type: string
            default: "03824"
          required: true
          
      responses:
        200:
          description: Successful response
          content:
            application/json: {}

        401:
           $ref: "#/components/responses/UnauthorizedError"
        404:
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found

components:
  securitySchemes:
    app_id:
      type: apiKey
      description: API key to authorize requests.
      name: appid
      in: query
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
