AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A Swagger UI for AWS API Gateway.

Parameters:
  SwaggerSpecURL:
    Type: String
    Default: https://petstore.swagger.io/v2/swagger.json
    Description: Enter a publicly accessible URL to the Swagger spec JSON/YAML.

Resources:
  SwaggerUiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: The Lambda function that serves the OpenWeather API.
      CodeUri: ./
      Handler: weatherapi.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          SWAGGER_SPEC_URL: !Ref SwaggerSpecURL
      Events:
        WeatherApi:
          Type: Api
          Properties:
            Path: /weather
            Method: GET

Outputs:
  SwaggerUiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather/
        
